#!/usr/bin/env bash
# =============================================================================
# 03-env-report.sh
# Aggregated environment report. Runs all three audit scripts in sequence,
# collects their JSON outputs, and produces a final consolidated report as
# both a terminal summary and a markdown file.
#
# Usage:  bash scripts/setup/03-env-report.sh
# Output: Terminal summary + ~/ai-workers-env-report-<date>.md
# =============================================================================

set -euo pipefail

CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_DATE=$(date +"%Y-%m-%d_%H%M%S")
MD_REPORT="$HOME/ai-workers-env-report-${REPORT_DATE}.md"

echo -e "${BOLD}${CYAN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     ai-workers  ·  Full Environment Report Runner         ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo "Running all audit scripts. This may take 30-60 seconds..."
echo ""

# ── Run each script, capture exit codes ───────────────────────────────────────
run_script() {
    local name="$1"
    local script="$2"
    echo -e "${BOLD}${CYAN}─────────────────────────────────────────${RESET}"
    echo -e "${BOLD} Running: ${name}${RESET}"
    echo -e "${BOLD}${CYAN}─────────────────────────────────────────${RESET}"
    bash "$script" || true   # Don't abort on non-zero exit
    echo ""
}

run_script "Preflight: Hardware & OS"  "${SCRIPT_DIR}/00-preflight-check.sh"
run_script "Software Audit"            "${SCRIPT_DIR}/01-software-audit.sh"
run_script "Port Conflict Audit"       "${SCRIPT_DIR}/02-port-audit.sh"

# ── Parse JSON reports ────────────────────────────────────────────────────────
PREFLIGHT_JSON="/tmp/preflight-report.json"
SOFTWARE_JSON="/tmp/software-audit.json"
PORT_JSON="/tmp/port-audit.json"

collect_issues() {
    local file="$1"
    local key="$2"
    if [[ -f "$file" ]]; then
        python3 -c "
import json, sys
try:
    data = json.load(open('${file}'))
    items = data.get('${key}', [])
    for item in items:
        print(item)
except: pass
" 2>/dev/null || true
    fi
}

ALL_CRITICAL=""
ALL_WARNINGS=""

for json_file in "$PREFLIGHT_JSON" "$SOFTWARE_JSON" "$PORT_JSON"; do
    c=$(collect_issues "$json_file" "critical_issues")
    w=$(collect_issues "$json_file" "warnings")
    [[ -n "$c" ]] && ALL_CRITICAL+="$c"$'\n'
    [[ -n "$w" ]] && ALL_WARNINGS+="$w"$'\n'
done

# Port conflicts go to critical
if [[ -f "$PORT_JSON" ]]; then
    pc=$(collect_issues "$PORT_JSON" "conflicts")
    [[ -n "$pc" ]] && ALL_CRITICAL+="$pc"$'\n'
fi

CRITICAL_COUNT=$(echo "$ALL_CRITICAL" | grep -c . || true)
WARNING_COUNT=$(echo "$ALL_WARNINGS" | grep -c . || true)

# ── Markdown Report ───────────────────────────────────────────────────────────
LAN_IP=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'src \K\S+' || hostname -I | awk '{print $1}')
HOSTNAME=$(hostname)

cat > "$MD_REPORT" << EOF
# ai-workers Environment Report

**Generated:** $(date "+%Y-%m-%d %H:%M:%S")
**Host:** ${HOSTNAME}
**LAN IP:** ${LAN_IP:-unknown}

---

## Overall Status

| Check | Result |
|-------|--------|
| Critical Issues | ${CRITICAL_COUNT} |
| Warnings | ${WARNING_COUNT} |
| Generated By | 03-env-report.sh |

---

## Critical Issues (Must Fix Before Build)

$(if [[ "$CRITICAL_COUNT" -eq 0 ]]; then
    echo "None. All critical checks passed."
else
    echo "$ALL_CRITICAL" | grep -v "^$" | while read -r issue; do
        echo "- **[CRITICAL]** ${issue}"
    done
fi)

---

## Warnings (Should Fix, Not Blockers)

$(if [[ "$WARNING_COUNT" -eq 0 ]]; then
    echo "None."
else
    echo "$ALL_WARNINGS" | grep -v "^$" | while read -r w; do
        echo "- **[WARN]** ${w}"
    done
fi)

---

## Quick Remediation Reference

### NVIDIA Driver (Critical for RTX 5070 Ti)
If \`nvidia-smi\` fails or driver version is < 570:
\`\`\`bash
sudo apt update
sudo apt install nvidia-driver-570 --no-install-recommends
sudo reboot
# After reboot:
nvidia-smi  # Should show driver version 570.x and GPU name
\`\`\`

### Docker Daemon Not Running
\`\`\`bash
sudo systemctl enable --now docker
sudo systemctl status docker
\`\`\`

### NVIDIA Container Toolkit (GPU in Docker)
\`\`\`bash
sudo apt install nvidia-container-toolkit
sudo nvidia-ctk runtime configure --runtime=docker
sudo systemctl restart docker
# Test:
docker run --rm --gpus all nvidia/cuda:12.0-base nvidia-smi
\`\`\`

### Open WebUI Port Mismatch (3000 vs 8080)
Edit \`~/open-webui/docker-compose.yml\`:
\`\`\`yaml
ports:
  - "8080:8080"   # Change from 3000:8080
\`\`\`

### Move Hardcoded Secrets to .env
For each service with hardcoded secrets in docker-compose.yml:
\`\`\`bash
# Create .env alongside docker-compose.yml
echo 'VARIABLE_NAME=value' >> ~/n8n/.env
echo 'VARIABLE_NAME=value' >> ~/open-webui/.env

# Reference in docker-compose.yml:
# environment:
#   - VARIABLE_NAME=\${VARIABLE_NAME}
\`\`\`
Then add \`.env\` to \`~/ai-workers/.gitignore\` (already done).

### Clean Orphaned Compose Backup Files
\`\`\`bash
find ~ -maxdepth 3 -name "*.bak*" -name "*.yml" -exec ls -lh {} \;
# Review, then delete confirmed orphans:
# rm ~/n8n/docker-compose.yml.bak ~/n8n/docker-compose.yml.bak2 ...
\`\`\`

### n8n WEBHOOK_URL for Slack Integration
Update \`~/n8n/docker-compose.yml\` after running cloudflared setup:
\`\`\`yaml
environment:
  - WEBHOOK_URL=https://YOUR-TUNNEL.trycloudflare.com/
\`\`\`
See \`scripts/setup/04-slack-tunnel-setup.sh\` for full tunnel setup.

---

## Service Dependency Build Order

Below is the recommended order for bringing up services, based on current state:

1. **NVIDIA driver** — install/update if not at 570+ (requires reboot)
2. **Docker daemon** — ensure running, NVIDIA Container Toolkit configured
3. **Ollama** — confirm running on :11434 with systemd service
4. **n8n** — start via \`docker compose up -d\` in ~/n8n/ ; update WEBHOOK_URL
5. **Open WebUI** — fix port mapping, start in ~/open-webui/
6. **ComfyUI** — start natively from ~/ComfyUI/ with GPU support
7. **Cloudflared tunnel** — expose n8n webhooks for Slack integration
8. **Slack App** — configure webhooks and slash commands
9. **Monitoring stack** — Portainer, Netdata, Uptime Kuma
10. **Plane** — bring up Docker stack in ~/plane-data/

---

## Raw Report Files

- Preflight: \`/tmp/preflight-report.json\`
- Software:  \`/tmp/software-audit.json\`
- Ports:     \`/tmp/port-audit.json\`

EOF

# ── Terminal Summary ───────────────────────────────────────────────────────────
echo -e "${BOLD}${CYAN}═══════════════════════════════════════════${RESET}"
echo -e "${BOLD}          FINAL SUMMARY${RESET}"
echo -e "${BOLD}${CYAN}═══════════════════════════════════════════${RESET}"
echo ""

if [[ "$CRITICAL_COUNT" -eq 0 ]]; then
    echo -e "  ${GREEN}${BOLD}No critical issues found.${RESET}"
else
    echo -e "  ${RED}${BOLD}${CRITICAL_COUNT} critical issue(s) — must fix before build:${RESET}"
    echo "$ALL_CRITICAL" | grep -v "^$" | while read -r issue; do
        echo -e "    ${RED}✗${RESET} ${issue}"
    done
fi

echo ""

if [[ "$WARNING_COUNT" -eq 0 ]]; then
    echo -e "  ${GREEN}No warnings.${RESET}"
else
    echo -e "  ${YELLOW}${BOLD}${WARNING_COUNT} warning(s):${RESET}"
    echo "$ALL_WARNINGS" | grep -v "^$" | while read -r w; do
        echo -e "    ${YELLOW}△${RESET} ${w}"
    done
fi

echo ""
echo -e "  ${CYAN}${BOLD}Full report:${RESET} ${MD_REPORT}"
echo ""
