#!/usr/bin/env bash
# =============================================================================
# 05-remediate-nosudo.sh
# Remediates all issues that do NOT require root/sudo:
#
#   1. Extracts hardcoded secrets from docker-compose files → .env files
#   2. Fixes Open WebUI port mapping (3000:8080 → 8080:8080)
#   3. Templates n8n WEBHOOK_URL to use env var (ngrok-ready)
#   4. Adds docker .env file references to compose files
#   5. Removes all orphaned .bak compose files
#   6. Creates .env.example templates for documentation
#
# Safe to re-run. All changes are backed up before modification.
# Requires: bash, sed, grep, python3
# Usage: bash scripts/setup/05-remediate-nosudo.sh
# =============================================================================

set -euo pipefail

CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'

info()  { echo -e "  ${CYAN}[INFO]${RESET} $1"; }
pass()  { echo -e "  ${GREEN}[DONE]${RESET} $1"; }
fail()  { echo -e "  ${RED}[FAIL]${RESET} $1"; }
warn()  { echo -e "  ${YELLOW}[WARN]${RESET} $1"; }
step()  { echo -e "\n${BOLD}${CYAN}── $1 ──${RESET}"; }
skip()  { echo -e "  ${CYAN}[SKIP]${RESET} $1 (already done)"; }

CHANGES_MADE=0
BACKUP_SUFFIX=".pre-remediate-$(date +%Y%m%d-%H%M%S)"

backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cp "$file" "${file}${BACKUP_SUFFIX}"
        info "Backed up: ${file} → $(basename ${file}${BACKUP_SUFFIX})"
    fi
}

echo -e "${BOLD}${CYAN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     ai-workers  ·  No-Sudo Remediation                    ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${RESET}"

# =============================================================================
# 1. n8n secrets → .env
# =============================================================================
step "1. n8n: Extract secrets to .env"

N8N_DIR="$HOME/n8n"
N8N_COMPOSE="${N8N_DIR}/docker-compose.yml"
N8N_ENV="${N8N_DIR}/.env"

if [[ ! -f "$N8N_COMPOSE" ]]; then
    warn "n8n docker-compose.yml not found at ${N8N_COMPOSE}. Skipping."
else
    # Extract current encryption key value
    ENCRYPTION_KEY=$(grep "N8N_ENCRYPTION_KEY" "$N8N_COMPOSE" 2>/dev/null \
        | grep -v "^\s*#" | head -1 \
        | sed 's/.*N8N_ENCRYPTION_KEY=//' | sed 's/  *#.*//' | xargs 2>/dev/null || echo "")

    if [[ -n "$ENCRYPTION_KEY" && "$ENCRYPTION_KEY" != '${N8N_ENCRYPTION_KEY}' ]]; then
        backup_file "$N8N_COMPOSE"

        # Write .env (only if key not already in it)
        if [[ ! -f "$N8N_ENV" ]] || ! grep -q "N8N_ENCRYPTION_KEY" "$N8N_ENV" 2>/dev/null; then
            {
                echo "# n8n secrets — DO NOT COMMIT THIS FILE"
                echo "# Generated by 05-remediate-nosudo.sh on $(date)"
                echo "N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}"
                echo ""
                echo "# Webhook URL — update after ngrok tunnel is running"
                echo "# Run: bash scripts/setup/04-slack-tunnel-setup.sh"
                echo "WEBHOOK_URL=http://localhost:5678/"
                echo ""
                echo "# Slack Incoming Webhook — paste after creating Slack App"
                echo "# See: services/n8n/slack-app-setup.md"
                echo "SLACK_INCOMING_WEBHOOK_URL="
            } > "$N8N_ENV"
            pass ".env created at ${N8N_ENV}"
            CHANGES_MADE=$((CHANGES_MADE + 1))
        else
            skip ".env already has N8N_ENCRYPTION_KEY"
        fi

        # Replace hardcoded key in compose with env var reference
        sed -i \
            "s|- N8N_ENCRYPTION_KEY=.*|- N8N_ENCRYPTION_KEY=\${N8N_ENCRYPTION_KEY}|" \
            "$N8N_COMPOSE"
        pass "docker-compose.yml: N8N_ENCRYPTION_KEY now references .env"
        CHANGES_MADE=$((CHANGES_MADE + 1))
    else
        skip "n8n encryption key already references env var"
    fi

    # Template WEBHOOK_URL to reference .env
    CURRENT_WEBHOOK=$(grep "WEBHOOK_URL" "$N8N_COMPOSE" 2>/dev/null \
        | grep -v "^\s*#" | head -1 \
        | sed 's/.*WEBHOOK_URL=//' | sed 's/  *#.*//' | xargs 2>/dev/null || echo "")

    if [[ -n "$CURRENT_WEBHOOK" && "$CURRENT_WEBHOOK" != '${WEBHOOK_URL}' ]]; then
        [[ ! -f "${N8N_COMPOSE}${BACKUP_SUFFIX}" ]] && backup_file "$N8N_COMPOSE"
        sed -i \
            "s|- WEBHOOK_URL=.*|- WEBHOOK_URL=\${WEBHOOK_URL}|" \
            "$N8N_COMPOSE"
        pass "docker-compose.yml: WEBHOOK_URL now references .env (update for ngrok tunnel)"
        CHANGES_MADE=$((CHANGES_MADE + 1))
    else
        skip "WEBHOOK_URL already references env var"
    fi

    # Add N8N_HOST change to LAN (0.0.0.0)
    CURRENT_HOST=$(grep "N8N_HOST=" "$N8N_COMPOSE" 2>/dev/null \
        | grep -v "^\s*#" | head -1 \
        | sed 's/.*N8N_HOST=//' | sed 's/  *#.*//' | xargs 2>/dev/null || echo "")
    if [[ "$CURRENT_HOST" == "localhost" ]]; then
        [[ ! -f "${N8N_COMPOSE}${BACKUP_SUFFIX}" ]] && backup_file "$N8N_COMPOSE"
        sed -i "s|- N8N_HOST=localhost|- N8N_HOST=0.0.0.0|" "$N8N_COMPOSE"
        pass "docker-compose.yml: N8N_HOST changed localhost → 0.0.0.0 (LAN accessible)"
        CHANGES_MADE=$((CHANGES_MADE + 1))
    fi

    # Write .env.example for documentation
    cat > "${N8N_DIR}/.env.example" << 'EOF'
# n8n environment variables
# Copy to .env and fill in values. Never commit .env.

# Encryption key for n8n credentials (generate: openssl rand -base64 32)
N8N_ENCRYPTION_KEY=CHANGE_ME

# Webhook base URL — set to ngrok tunnel URL after running:
# bash ~/ai-workers/scripts/setup/04-slack-tunnel-setup.sh
WEBHOOK_URL=https://YOUR-TUNNEL-URL/

# Slack Incoming Webhook URL (from Slack App → Incoming Webhooks)
# See: ~/ai-workers/services/n8n/slack-app-setup.md
SLACK_INCOMING_WEBHOOK_URL=https://hooks.slack.com/services/...
EOF
    pass ".env.example written to ${N8N_DIR}"
fi

# =============================================================================
# 2. Open WebUI secrets → .env + fix port mapping
# =============================================================================
step "2. Open WebUI: Secrets, .env, and port fix"

OW_DIR="$HOME/open-webui"
OW_COMPOSE="${OW_DIR}/docker-compose.yml"
OW_ENV="${OW_DIR}/.env"

if [[ ! -f "$OW_COMPOSE" ]]; then
    warn "open-webui docker-compose.yml not found. Skipping."
else
    # Extract WEBUI_SECRET_KEY
    SECRET_KEY=$(grep "WEBUI_SECRET_KEY" "$OW_COMPOSE" 2>/dev/null \
        | grep -v "^\s*#" | head -1 \
        | sed 's/.*WEBUI_SECRET_KEY=//' | sed 's/  *#.*//' | xargs 2>/dev/null || echo "")

    if [[ -n "$SECRET_KEY" && "$SECRET_KEY" != '${WEBUI_SECRET_KEY}' ]]; then
        backup_file "$OW_COMPOSE"

        if [[ ! -f "$OW_ENV" ]] || ! grep -q "WEBUI_SECRET_KEY" "$OW_ENV" 2>/dev/null; then
            {
                echo "# Open WebUI secrets — DO NOT COMMIT THIS FILE"
                echo "# Generated by 05-remediate-nosudo.sh on $(date)"
                echo "WEBUI_SECRET_KEY=${SECRET_KEY}"
                echo ""
                echo "# Ollama API base URL"
                echo "OLLAMA_API_BASE_URL=http://host.docker.internal:11434"
            } > "$OW_ENV"
            pass ".env created at ${OW_ENV}"
            CHANGES_MADE=$((CHANGES_MADE + 1))
        fi

        sed -i \
            "s|- WEBUI_SECRET_KEY=.*|- WEBUI_SECRET_KEY=\${WEBUI_SECRET_KEY}|" \
            "$OW_COMPOSE"
        pass "docker-compose.yml: WEBUI_SECRET_KEY now references .env"
        CHANGES_MADE=$((CHANGES_MADE + 1))
    else
        skip "WEBUI_SECRET_KEY already references env var"
    fi

    # Fix port mapping: 3000:8080 → 8080:8080 (align with architecture docs)
    if grep -q '"3000:8080"' "$OW_COMPOSE" 2>/dev/null; then
        [[ ! -f "${OW_COMPOSE}${BACKUP_SUFFIX}" ]] && backup_file "$OW_COMPOSE"
        sed -i 's/"3000:8080"/"8080:8080"/' "$OW_COMPOSE"
        pass "Port mapping fixed: 3000:8080 → 8080:8080 (matches architecture spec)"
        CHANGES_MADE=$((CHANGES_MADE + 1))
    else
        skip "Port mapping already correct or not using 3000"
    fi

    # Write .env.example
    cat > "${OW_DIR}/.env.example" << 'EOF'
# Open WebUI environment variables
# Copy to .env and fill in values. Never commit .env.

# Secret key for session signing (generate: openssl rand -base64 32)
WEBUI_SECRET_KEY=CHANGE_ME

# Ollama API URL (use host.docker.internal when running in Docker)
OLLAMA_API_BASE_URL=http://host.docker.internal:11434
EOF
    pass ".env.example written to ${OW_DIR}"
fi

# =============================================================================
# 3. Clean up orphaned .bak files
# =============================================================================
step "3. Remove orphaned .bak compose files"

BAK_DIRS=("$HOME/n8n" "$HOME/open-webui")
REMOVED=0

for dir in "${BAK_DIRS[@]}"; do
    if [[ -d "$dir" ]]; then
        # Find all .bak variants — .bak, .bak2, .bak3, .bakN, .bak.TIMESTAMP
        while IFS= read -r -d '' bak_file; do
            rm -f "$bak_file"
            info "Removed: ${bak_file}"
            REMOVED=$((REMOVED + 1))
        done < <(find "$dir" -maxdepth 1 \
            \( -name "*.bak" -o -name "*.bak[0-9]*" -o -name "*.bak.*" \) \
            -print0 2>/dev/null)
    fi
done

if [[ "$REMOVED" -gt 0 ]]; then
    pass "Removed ${REMOVED} orphaned .bak file(s)"
    CHANGES_MADE=$((CHANGES_MADE + 1))
else
    skip "No .bak files found to remove"
fi

# =============================================================================
# 4. Ensure .env files are in .gitignore for each service dir
# =============================================================================
step "4. Verify .gitignore protects .env files"

AI_WORKERS_GITIGNORE="$HOME/ai-workers/.gitignore"
if [[ -f "$AI_WORKERS_GITIGNORE" ]]; then
    if grep -q "^\.env$" "$AI_WORKERS_GITIGNORE" 2>/dev/null; then
        pass ".gitignore already excludes .env files"
    else
        echo "" >> "$AI_WORKERS_GITIGNORE"
        echo "# Service .env files (secrets)" >> "$AI_WORKERS_GITIGNORE"
        echo ".env" >> "$AI_WORKERS_GITIGNORE"
        pass ".gitignore updated to exclude .env files"
        CHANGES_MADE=$((CHANGES_MADE + 1))
    fi
fi

# =============================================================================
# 5. Show final state of compose files
# =============================================================================
step "5. Verification"

echo ""
info "n8n docker-compose.yml (sensitive lines):"
grep -E "ENCRYPTION_KEY|WEBHOOK_URL|N8N_HOST|SECRET" "$N8N_COMPOSE" 2>/dev/null \
    | while read -r line; do info "  $line"; done

echo ""
info "open-webui docker-compose.yml (sensitive lines):"
grep -E "SECRET|port|PORT" "$OW_COMPOSE" 2>/dev/null \
    | while read -r line; do info "  $line"; done

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${BOLD}${CYAN}══ Summary ══${RESET}"
echo ""

if [[ "$CHANGES_MADE" -gt 0 ]]; then
    pass "${CHANGES_MADE} change(s) applied successfully."
    echo ""
    echo -e "  ${BOLD}Recommended next step:${RESET}"
    echo "  Run the sudo remediation to fix NVIDIA device files and Docker:"
    echo ""
    echo -e "  ${BOLD}  sudo bash ~/ai-workers/scripts/setup/06-remediate-sudo.sh${RESET}"
else
    pass "Everything was already clean. No changes needed."
fi
echo ""
